# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  tags:
    release-*:
     - step:
        script:
         - git remote add github_sync git@github.com:RodrigoNaves/ginan-bitbucket-update-tests.git
         - git remote -v
         - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
         - git show-ref
         - git pull origin $BITBUCKET_TAG
         - git push --force github_sync $BITBUCKET_TAG
         - git remote rm github_sync